version: "2"

services:

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./docker/registry/config.yml:/etc/docker/registry/config.yml
  
  mysql:
    image: mysql:latest
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      # uniquement pour connection de debug depuis l'extérieur du container
      - "3306:3306"

  mq:
    build: ./resources/bytearena-message-broker
    environment:
      - PORT=80
      - CHANNELS=agent
  
  dotgit:
    depends_on: ["mysql"]
    build:
      context: $GOPATH/src/github.com/bytearena
      dockerfile: $GOPATH/src/github.com/bytearena/bytearena/docker/dotgit/Dockerfile
      args:
        GIT_ADMIN_KEY_PUBLIC: ${GIT_ADMIN_KEY_PUBLIC}
        DATABASE_URI: "${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST}:${DATABASE_PORT})/${DATABASE_NAME}?charset=utf8"
        GIT_REPOSITORIES_PATH: "/home/git/repositories"
        API_PORT: 8888
    links:
      - mq
      - mysql
    volumes:
      - ./data/repositories:/home/git/repositories
      - $GOPATH/src/github.com/bytearena/dotgit:/go/src/github.com/bytearena/dotgit
      - $GOPATH/src/github.com/bytearena/bytearena/docker/dotgit/start.sh:/go/src/github.com/bytearena/dotgit/start.sh
    ports:
      - "22:22"
      - "9418:9418"
      # uniquement pour connection de debug depuis l'extérieur du container
      - "8888:8888"

  agentbuilder:
    depends_on: ["mq"]
    build:
      dockerfile: ./docker/agent-builder/Dockerfile
      context: .
      args:
        GIT_ADMIN_KEY_PRIVATE: ${GIT_ADMIN_KEY_PRIVATE}
    environment:
      - PORT=80
      - GIT_HOST=gandalf
      - REGISTRY_HOST=registry
      - MQ_HOST=mq
    links:
      - registry
      - mq
