version: "2"

services:

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./docker/registry/config.yml:/etc/docker/registry/config.yml
    networks:
      - private

  gandalf:
    build: ./docker/gandalf
    networks:
      - private
    volumes:
      - ./data/repositories:/home/git/repositories
    ports:
      - "8000:8000"
      - "443:443"
      - "22:22"
      - "9418:9418"

  mongodb:
    image: tutum/mongodb:3.0
    environment:
      # - MONGODB_PASS=admin
      - AUTH=no

  agentbuilder:
    build:
      dockerfile: ./docker/agent-builder/Dockerfile
      context: .
    environment:
      - PORT=80
      - REGISTRY_HOST=registry
      - GIT_HOST=gandalf
    networks:
      - private

  webhook:
    build: ./docker/webhook
    networks:
      - private

  jump-host:
    image: ubuntu
    networks:
      - private

networks:
  private:
    driver: bridge
