version: "2"

services:

  registry:
    build: ./docker/registry

  mq:
    build: $GOPATH/src/github.com/bytearena/bytearena-message-broker
    environment:
      - PORT=80
      - CHANNELS=agent,viz,ping,arena

  dotgit:
    build:
      context: $GOPATH/src/github.com/bytearena
      dockerfile: $GOPATH/src/github.com/bytearena/bytearena/docker/dotgit/Dockerfile
      args:
        DATABASE_URI: "${GRAPHQL_URL}"
        GIT_REPOSITORIES_PATH: "/tmp/repositories"
    volumes:
      - ./data/repositories:/tmp/repositories
    links:
      - mq
    environment:
      - MYSQL_HOST=${DATABASE_HOST}
    ports:
      # le port 22 est utilisé par le routeur HAproxy, et route vers dotgit 2222
      - "22:22"
      # Le port du protocole git; voir issue bytearena/bytearena#58
      - "9418:9418"

  agentbuilder:
    depends_on: ["mq"]
    build:
      dockerfile: ./docker/agent-builder/Dockerfile
      context: .
      args:
        GIT_ADMIN_KEY_PRIVATE: ${GIT_ADMIN_KEY_PRIVATE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=80
      - GIT_HOST=dotgit
      - REGISTRY_HOST=localhost
      - MQ_HOST=mq
    links:
      - registry
      - mq
