version: "2"

services:

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./docker/registry/config.yml:/etc/docker/registry/config.yml

  mongodb:
    image: tutum/mongodb:3.0
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      # - MONGODB_PASS=admin
      - AUTH=no

  gandalf:
    build:
      dockerfile: ./docker/gandalf/Dockerfile
      context: .
      args:
        GIT_ADMIN_KEY_PUBLIC: ${GIT_ADMIN_KEY_PUBLIC}
    links:
      - mongodb
      - mq
    volumes:
      - ./data/repositories:/home/git/repositories
    ports:
      - "8000:8000"
      - "443:443"
      - "22:22"
      - "9418:9418"

  mq:
    build: ./resources/bytearena-message-broker
    environment:
      - PORT=80
      - CHANNELS=agent

  agentbuilder:
    build:
      dockerfile: ./docker/agent-builder/Dockerfile
      context: .
      args:
        GIT_ADMIN_KEY_PRIVATE: ${GIT_ADMIN_KEY_PRIVATE}
    environment:
      - PORT=80
      - GIT_HOST=gandalf
      - REGISTRY_HOST=registry
      - MQ_HOST=mq
    links:
      - registry
      - mq
