version: "2"

services:

  registry:
    build: ./docker/registry
    ports:
      - "5000:5000"

  mq:
    build: $GOPATH/src/github.com/bytearena/bytearena-message-broker
    environment:
      - PORT=80
      - CHANNELS=agent

  dotgit:
    build:
      context: $GOPATH/src/github.com/bytearena
      dockerfile: $GOPATH/src/github.com/bytearena/bytearena/docker/dotgit/Dockerfile
      args:
        GIT_ADMIN_KEY_PUBLIC: ${GIT_ADMIN_KEY_PUBLIC}
        DATABASE_URI: "${DATABASE_USER}:${DATABASE_PASSWORD}@tcp(${DATABASE_HOST}:${DATABASE_PORT})/${DATABASE_NAME}?charset=utf8"
        GIT_REPOSITORIES_PATH: "/home/git/repositories"
        API_PORT: 8888
    links:
      - mq
    ports:
      - "22:22"
      - "9418:9418"
      # uniquement pour connection de debug depuis l'extérieur du container
      - "8888:8888"

  agentbuilder:
    depends_on: ["mq"]
    build:
      dockerfile: ./docker/agent-builder/Dockerfile
      context: .
      args:
        GIT_ADMIN_KEY_PRIVATE: ${GIT_ADMIN_KEY_PRIVATE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=80
      - GIT_HOST=dotgit
      - REGISTRY_HOST=localhost
      - MQ_HOST=mq
    links:
      - registry
      - mq
