version: "2"

services:

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./docker/registry/config.yml:/etc/docker/registry/config.yml

  mongodb:
    image: tutum/mongodb:3.0
    ports:
      - "27017:27017"
    environment:
      # - MONGODB_PASS=admin
      - AUTH=no

  gandalf:
    build: ./docker/gandalf
    links:
      - mongodb
    volumes:
      - ./data/repositories:/home/git/repositories
    ports:
      - "8000:8000"
      - "443:443"
      - "22:22"
      - "9418:9418"

  agentbuilder:
    build:
      dockerfile: ./docker/agent-builder/Dockerfile
      context: .
    environment:
      - PORT=80
      - GIT_HOST=gandalf
      - REGISTRY_HOST=registry
    links:
      - registry
