#!/bin/sh

#set -x # echo on
#env | grep GIT

# Available variables :
# $GIT_USER         : the dotgit user (in db) authentified by the SSH public key; usually the same as owner, but can be different when an administrative account operates on repos
# $GIT_REPO_OWNER   : the dotgit user (in db) to whom the operated GIT repository belongs
# $GIT_REPO_NAME    : the name of the repository, without the owner name
# $GIT_REPO_PATH    : the full path of the repository on disk
# $GIT_CLONE_URL    : clone url for repo
# $GIT_OPERATION    : the current git operation (one of "receive-pack", "upload-pack")

/usr/bin/agentbuilder-cli \
    --repourl "$GIT_REPO_PATH" \
    --imagename "$GIT_REPO_NAME"

exit_status=$?
if [ $exit_status -ne 0 ]; then
    echo "ERROR: your agent could not be built properly."
else
    /usr/bin/mq-cli \
        --mqhost="$MQ_HOST" \
        --publish agent:repo.pushed \
        --data "{\"username\":\"$GIT_REPO_OWNER\",\"repo\":\"$GIT_REPO_NAME\",\"cloneurl\":\"$GIT_CLONE_URL\"}"
fi

exit $exit_status
