#!/bin/sh

set -x # echo on

REPOS_DIR="$HOME/repositories"
REPO=$(echo $PWD | sed -e "s#$REPOS_DIR/##g")

curl http://mq/pub/agent/repo.pushed \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"$TSURU_USER\",\"repo\":\"$REPO\"}"
