// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mapcontainer

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer(in *jlexer.Lexer, out *Mesh) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "vertices":
			if in.IsNull() {
				in.Skip()
				out.Vertices = nil
			} else {
				in.Delim('[')
				if out.Vertices == nil {
					if !in.IsDelim(']') {
						out.Vertices = make([]float64, 0, 8)
					} else {
						out.Vertices = []float64{}
					}
				} else {
					out.Vertices = (out.Vertices)[:0]
				}
				for !in.IsDelim(']') {
					var v1 float64
					v1 = float64(in.Float64())
					out.Vertices = append(out.Vertices, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "indices":
			if in.IsNull() {
				in.Skip()
				out.Indices = nil
			} else {
				in.Delim('[')
				if out.Indices == nil {
					if !in.IsDelim(']') {
						out.Indices = make([]int, 0, 8)
					} else {
						out.Indices = []int{}
					}
				} else {
					out.Indices = (out.Indices)[:0]
				}
				for !in.IsDelim(']') {
					var v2 int
					v2 = int(in.Int())
					out.Indices = append(out.Indices, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "uvs":
			if in.IsNull() {
				in.Skip()
				out.Uvs = nil
			} else {
				in.Delim('[')
				if out.Uvs == nil {
					if !in.IsDelim(']') {
						out.Uvs = make([]float64, 0, 8)
					} else {
						out.Uvs = []float64{}
					}
				} else {
					out.Uvs = (out.Uvs)[:0]
				}
				for !in.IsDelim(']') {
					var v3 float64
					v3 = float64(in.Float64())
					out.Uvs = append(out.Uvs, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer(out *jwriter.Writer, in Mesh) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"vertices\":")
	if in.Vertices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v4, v5 := range in.Vertices {
			if v4 > 0 {
				out.RawByte(',')
			}
			out.Float64(float64(v5))
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"indices\":")
	if in.Indices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v6, v7 := range in.Indices {
			if v6 > 0 {
				out.RawByte(',')
			}
			out.Int(int(v7))
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"uvs\":")
	if in.Uvs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in.Uvs {
			if v8 > 0 {
				out.RawByte(',')
			}
			out.Float64(float64(v9))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Mesh) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Mesh) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Mesh) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Mesh) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer(l, v)
}
func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer1(in *jlexer.Lexer, out *MapStart) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "point":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v10 := 0
				for !in.IsDelim(']') {
					if v10 < 2 {
						out.Point[v10] = float64(in.Float64())
						v10++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer1(out *jwriter.Writer, in MapStart) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"point\":")
	out.RawByte('[')
	for v11 := range in.Point {
		if v11 > 0 {
			out.RawByte(',')
		}
		out.Float64(float64(in.Point[v11]))
	}
	out.RawByte(']')
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MapStart) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapStart) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapStart) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapStart) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer1(l, v)
}
func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer2(in *jlexer.Lexer, out *MapPolygon) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "points":
			if in.IsNull() {
				in.Skip()
				out.Points = nil
			} else {
				in.Delim('[')
				if out.Points == nil {
					if !in.IsDelim(']') {
						out.Points = make([]MapPoint, 0, 4)
					} else {
						out.Points = []MapPoint{}
					}
				} else {
					out.Points = (out.Points)[:0]
				}
				for !in.IsDelim(']') {
					var v12 MapPoint
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v13 := 0
						for !in.IsDelim(']') {
							if v13 < 2 {
								v12[v13] = float64(in.Float64())
								v13++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Points = append(out.Points, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer2(out *jwriter.Writer, in MapPolygon) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"points\":")
	if in.Points == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v14, v15 := range in.Points {
			if v14 > 0 {
				out.RawByte(',')
			}
			out.RawByte('[')
			for v16 := range v15 {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.Float64(float64(v15[v16]))
			}
			out.RawByte(']')
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MapPolygon) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapPolygon) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapPolygon) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapPolygon) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer2(l, v)
}
func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer3(in *jlexer.Lexer, out *MapObstacleObject) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "polygon":
			(out.Polygon).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer3(out *jwriter.Writer, in MapObstacleObject) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"polygon\":")
	(in.Polygon).MarshalEasyJSON(out)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MapObstacleObject) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapObstacleObject) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapObstacleObject) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapObstacleObject) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer3(l, v)
}
func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer4(in *jlexer.Lexer, out *MapGround) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "polygon":
			(out.Polygon).UnmarshalEasyJSON(in)
		case "mesh":
			(out.Mesh).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer4(out *jwriter.Writer, in MapGround) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"polygon\":")
	(in.Polygon).MarshalEasyJSON(out)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"mesh\":")
	(in.Mesh).MarshalEasyJSON(out)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MapGround) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapGround) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapGround) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapGround) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer4(l, v)
}
func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer5(in *jlexer.Lexer, out *MapContainer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "meta":
			easyjsonFa548efbDecode(in, &out.Meta)
		case "data":
			easyjsonFa548efbDecode1(in, &out.Data)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer5(out *jwriter.Writer, in MapContainer) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"meta\":")
	easyjsonFa548efbEncode(out, in.Meta)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	easyjsonFa548efbEncode1(out, in.Data)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MapContainer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapContainer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapContainer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapContainer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer5(l, v)
}
func easyjsonFa548efbDecode1(in *jlexer.Lexer, out *struct {
	Grounds         []MapGround         `json:"grounds"`
	Starts          []MapStart          `json:"starts"`
	Obstacles       []MapObstacleObject `json:"obstacles"`
	CollisionMeshes []CollisionMesh     `json:"collisionmeshes"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "grounds":
			if in.IsNull() {
				in.Skip()
				out.Grounds = nil
			} else {
				in.Delim('[')
				if out.Grounds == nil {
					if !in.IsDelim(']') {
						out.Grounds = make([]MapGround, 0, 1)
					} else {
						out.Grounds = []MapGround{}
					}
				} else {
					out.Grounds = (out.Grounds)[:0]
				}
				for !in.IsDelim(']') {
					var v17 MapGround
					(v17).UnmarshalEasyJSON(in)
					out.Grounds = append(out.Grounds, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "starts":
			if in.IsNull() {
				in.Skip()
				out.Starts = nil
			} else {
				in.Delim('[')
				if out.Starts == nil {
					if !in.IsDelim(']') {
						out.Starts = make([]MapStart, 0, 1)
					} else {
						out.Starts = []MapStart{}
					}
				} else {
					out.Starts = (out.Starts)[:0]
				}
				for !in.IsDelim(']') {
					var v18 MapStart
					(v18).UnmarshalEasyJSON(in)
					out.Starts = append(out.Starts, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "obstacles":
			if in.IsNull() {
				in.Skip()
				out.Obstacles = nil
			} else {
				in.Delim('[')
				if out.Obstacles == nil {
					if !in.IsDelim(']') {
						out.Obstacles = make([]MapObstacleObject, 0, 1)
					} else {
						out.Obstacles = []MapObstacleObject{}
					}
				} else {
					out.Obstacles = (out.Obstacles)[:0]
				}
				for !in.IsDelim(']') {
					var v19 MapObstacleObject
					(v19).UnmarshalEasyJSON(in)
					out.Obstacles = append(out.Obstacles, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "collisionmeshes":
			if in.IsNull() {
				in.Skip()
				out.CollisionMeshes = nil
			} else {
				in.Delim('[')
				if out.CollisionMeshes == nil {
					if !in.IsDelim(']') {
						out.CollisionMeshes = make([]CollisionMesh, 0, 1)
					} else {
						out.CollisionMeshes = []CollisionMesh{}
					}
				} else {
					out.CollisionMeshes = (out.CollisionMeshes)[:0]
				}
				for !in.IsDelim(']') {
					var v20 CollisionMesh
					(v20).UnmarshalEasyJSON(in)
					out.CollisionMeshes = append(out.CollisionMeshes, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncode1(out *jwriter.Writer, in struct {
	Grounds         []MapGround         `json:"grounds"`
	Starts          []MapStart          `json:"starts"`
	Obstacles       []MapObstacleObject `json:"obstacles"`
	CollisionMeshes []CollisionMesh     `json:"collisionmeshes"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"grounds\":")
	if in.Grounds == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v21, v22 := range in.Grounds {
			if v21 > 0 {
				out.RawByte(',')
			}
			(v22).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"starts\":")
	if in.Starts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v23, v24 := range in.Starts {
			if v23 > 0 {
				out.RawByte(',')
			}
			(v24).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"obstacles\":")
	if in.Obstacles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v25, v26 := range in.Obstacles {
			if v25 > 0 {
				out.RawByte(',')
			}
			(v26).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"collisionmeshes\":")
	if in.CollisionMeshes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v27, v28 := range in.CollisionMeshes {
			if v27 > 0 {
				out.RawByte(',')
			}
			(v28).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjsonFa548efbDecode(in *jlexer.Lexer, out *struct {
	Readme         string `json:"readme"`
	Kind           string `json:"kind"`
	MaxContestants int    `json:"maxcontestants"`
	Date           string `json:"date"`
	Repository     string `json:"repository"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "readme":
			out.Readme = string(in.String())
		case "kind":
			out.Kind = string(in.String())
		case "maxcontestants":
			out.MaxContestants = int(in.Int())
		case "date":
			out.Date = string(in.String())
		case "repository":
			out.Repository = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncode(out *jwriter.Writer, in struct {
	Readme         string `json:"readme"`
	Kind           string `json:"kind"`
	MaxContestants int    `json:"maxcontestants"`
	Date           string `json:"date"`
	Repository     string `json:"repository"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"readme\":")
	out.String(string(in.Readme))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"kind\":")
	out.String(string(in.Kind))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"maxcontestants\":")
	out.Int(int(in.MaxContestants))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"date\":")
	out.String(string(in.Date))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"repository\":")
	out.String(string(in.Repository))
	out.RawByte('}')
}
func easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer6(in *jlexer.Lexer, out *CollisionMesh) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "vertices":
			if in.IsNull() {
				in.Skip()
				out.Vertices = nil
			} else {
				in.Delim('[')
				if out.Vertices == nil {
					if !in.IsDelim(']') {
						out.Vertices = make([]float64, 0, 8)
					} else {
						out.Vertices = []float64{}
					}
				} else {
					out.Vertices = (out.Vertices)[:0]
				}
				for !in.IsDelim(']') {
					var v29 float64
					v29 = float64(in.Float64())
					out.Vertices = append(out.Vertices, v29)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer6(out *jwriter.Writer, in CollisionMesh) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.String(string(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"vertices\":")
	if in.Vertices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v30, v31 := range in.Vertices {
			if v30 > 0 {
				out.RawByte(',')
			}
			out.Float64(float64(v31))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CollisionMesh) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CollisionMesh) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa548efbEncodeGithubComBytearenaBytearenaCommonTypesMapcontainer6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CollisionMesh) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CollisionMesh) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa548efbDecodeGithubComBytearenaBytearenaCommonTypesMapcontainer6(l, v)
}
